# Generated by Django 5.0.4 on 2024-04-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmihistory',
            name='condition',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
